"""add work_sessions

Revision ID: 4ff40a28ca82
Revises: 89bca10a10f8
Create Date: 2026-06-27 18:13:16.176986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff40a28ca82'
down_revision: Union[str, Sequence[str], None] = '89bca10a10f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('shifts', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('shifts', sa.Column('started_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shifts', 'users', ['started_by_id'], ['id'])
    op.drop_column('shifts', 'status')
    op.drop_column('shifts', 'comment')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.add_column('shifts', sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='shiftstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'started_by_id')
    op.drop_column('shifts', 'ended_at')
    op.drop_column('shifts', 'started_at')
    # ### end Alembic commands ###
