"""initial_schema

Revision ID: 89bca10a10f8
Revises: 
Create Date: 2026-06-26 04:06:52.129397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bca10a10f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('machine_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rails',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('length', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pieces_per_pack', sa.Integer(), nullable=False),
    sa.Column('metal', sa.Enum('ALUMINUM', 'ZINC', name='metaltype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shifts',
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('DAY', 'NIGHT', name='shifttype'), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='shiftstatus'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MECHANIC', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('machine_rails',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('rail_id', sa.Integer(), nullable=False),
    sa.Column('operator_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mechanic_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['rail_id'], ['rails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'rail_id', name='uq_machine_rail')
    )
    op.create_table('production_entries',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('rail_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('packs', sa.Integer(), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=False),
    sa.Column('meters', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('operator_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mechanic_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operator_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mechanic_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rail_length', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pieces_per_pack', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rail_id'], ['rails.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_mechanics',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_type', sa.Enum('MAIN', 'ASSISTANT', name='mechanictype'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_mechanics')
    op.drop_table('production_entries')
    op.drop_table('machine_rails')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('shifts')
    op.drop_table('rails')
    op.drop_table('machines')
    # ### end Alembic commands ###
